services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres-test:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-test:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres
    
  backend:
    container_name: backend_container
    build:
      context: ../backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENET: Development
    volumes:
      - ../backend:/app
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - backend_net

  frontend:
    container_name: frontend_container
    build:
      context: ../frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
    volumes:
      - ../frontend:/app
    ports:
      - "4200:80"
    networks:
      - frontend_net

networks:
  postgres:
    driver: bridge
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge

volumes:
  postgres-test:
  pgadmin-test: